[package]
name = "shimzon"
version = "0.1.0"
authors = ["QAston <qaston@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
toml="0.5.8"
serde = "1.0.97"
serde_derive = "1.0"
clap = "2.33.3"
